# Generated by Django 4.2.2 on 2023-06-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industries',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
