apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contact-api
  template:
    metadata:
      labels:
        app: contact-api
    spec:
      containers:
        - name: contact-api
          image: lancerprince/contact
          ports:
            - containerPort: 8000
              