apiVersion: v1
kind: Service
metadata:
  name: contact-api
spec:
  selector:
    app: contact-api  # Label selector to match the MySQL pods
  ports:
    - name: contact-api
      port: 8000
      targetPort: 8000
      nodePort: 30080
  type: NodePort
