apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql  # Label selector to match the MySQL pods
  ports:
    - name: mysql-port
      protocol: TCP
      port: 3306  # Port on which MySQL is running inside the container
      targetPort: 3306  # Port on which MySQL is listening inside the container
  type: ClusterIP  # Type of service. ClusterIP exposes the service internally within the cluster
